### ISSUE TITLE
Advertise LoadBalancer Ingress IPs

### ISSUE THREAD

**Issue by bensallen** [projectcalico/confd#301]
#266 added support for advertising whitelisted `svc.Spec.ExternalIPs`. To interoperate with MetalLB and possibly other controllers that set `[]v1.LoadBalancerIngress` via `svc.Status.LoadBalancer.Ingress`, it would be useful to also announce load balancer provided IPs.

For example from MetalLB: https://github.com/danderson/metallb/blob/master/controller/service.go#L135.

This feature will allow just the controller component of MetalLB to be used for IPAM and Calico for announcing.

**Comment by bensallen** [comment]
Should this be an additional BGPConfiguration attribute, eg.

```
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: true
  asNumber: 63400
  serviceClusterIPs:
  - cidr: 10.96.0.0/12
  serviceExternalIPs:
  - cidr: 104.244.42.129/32
  - cidr: 172.217.3.0/24
  serviceLoadBalancerIPs:
  - cidr: 192.168.12.65/32
  - cidr: 10.0.4.0/24
```

Seems like it would be useful to control announcing of IPs via `svc.Status.LoadBalancer.Ingress` separately from ExternalIPs. Looks like the changes from https://github.com/projectcalico/libcalico-go/pull/1123 and #266, can for the most part be used as a template for this work.

Alternatively, we could overload serviceExternalIPs to include load balancer IPs and just extend `func (rg *routeGenerator) getAllRoutesForService(svc *v1.Service) []string` with something like:

```
	if svc.Status.LoadBalancer.Ingress != nil {
		for _, lbIngress := range svc.Status.LoadBalancer.Ingress {

			if lbIngress.IP == "" {
				continue
			}

			// Only advertise whitelisted external IPs
			if !rg.isAllowedExternalIP(lbIngress.IP) {
				svc := fmt.Sprintf("%s/%s", svc.Namespace, svc.Name)
				log.WithFields(log.Fields{"ip": lbIngress.IP, "svc": svc}).Info("Cannot advertise Load Balancer IP - not whitelisted")
				continue
			}
			routes = append(routes, lbIngress.IP)
		}
	}
```
